# Generated by Django 5.1.2 on 2024-10-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0002_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.IntegerField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
