# Generated by Django 5.1.2 on 2024-10-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0003_alter_student_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digital', models.IntegerField()),
                ('cprogramming', models.IntegerField()),
                ('cfa', models.IntegerField()),
                ('english', models.IntegerField()),
            ],
        ),
    ]
